name: CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn ci:install

      - name: Run linter
        run: yarn lint:typecheck
